name: Conditional Sync Fork, Build and Push Docker Image

on:
  schedule:
    - cron: '0 * * * *'  # ogni ora
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  sync-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/nzo66/mediaflow-proxy.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Force sync fork from upstream, preserve workflow
        id: sync
        run: |
          # Controlla se ci sono differenze PRIMA del reset
          if git diff --quiet HEAD upstream/main; then
            echo "Repository already up to date"
            echo "no_change=true" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, proceeding with sync and build"
            cp .github/workflows/sync-build-push.yml /tmp/sync-build-push.yml
            git reset --hard upstream/main
            mkdir -p .github/workflows
            mv /tmp/sync-build-push.yml .github/workflows/sync-build-push.yml
            git add .
            git commit -m "Restore workflow after forced sync" || echo "No changes needed"
            git push origin main --force
            echo "no_change=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if build is needed
        run: echo "Changes detected, proceed with build."
        if: steps.sync.outputs.no_change == 'false'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.sync.outputs.no_change == 'false'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.sync.outputs.no_change == 'false'

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dula117/mediaflow-proxy:latest
        if: steps.sync.outputs.no_change == 'false'
